load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "util_lib",
    hdrs = ["inc/util/util.hpp"],  
    srcs = ["src/util.cpp"],
    includes = ["inc/"],
    visibility = ["//visibility:public"]
)
